"""Rendering the report (R2, spec §7.4): fixed sections, in a fixed order, as Markdown.

The output depends on nothing but its input: with ``--today`` fixed, the same data
renders the same bytes (AC7), which is what the golden files in the tests pin down.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Sequence
from dataclasses import dataclass

from portfolio_ops.model import Diagnostic
from portfolio_ops.report import SECTIONS, ReportInput, title
from portfolio_ops.report import sections as _sections  # noqa: F401 — registers the sections

LEFT_OUT = (
    "Stale, Escalations, Overdue reviews, Focus and Health are left out until the data validates."
)


@dataclass(frozen=True)
class Rendered:
    title: str
    markdown: str
    has_items: bool  # §7.4: sections 1–4 non-empty, or no focus this week


def _header(today: dt.date) -> list[str]:
    return [f"# {title(today)}", "", f"Generated by portfolio-ops for {today} (UTC)."]


def render(data: ReportInput) -> Rendered:
    lines = _header(data.today)
    has_items = False
    for position in sorted(SECTIONS):
        part = SECTIONS[position](data)
        lines += ["", f"## {part.title}", "", *part.lines]
        has_items = has_items or part.has_items
    return Rendered(title(data.today), "\n".join(lines) + "\n", has_items)


def render_invalid(errors: Sequence[Diagnostic], prefix: str, today: dt.date) -> Rendered:
    """Section 1 alone: the data does not validate, so nothing else can be trusted."""
    lines = _header(today)
    lines += ["", "## Validation errors", "", "```text"]
    lines += [error.render(prefix) for error in errors]
    lines += ["```", "", LEFT_OUT]
    return Rendered(title(today), "\n".join(lines) + "\n", True)
