"""Rendering the report (R2, spec §7.4): fixed sections, in a fixed order, as Markdown.

The output depends on nothing but its input: with ``--today`` fixed, the same data
renders the same bytes (AC7), which is what the golden files in the tests pin down.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Sequence
from dataclasses import dataclass

from portfolio_ops.model import Diagnostic
from portfolio_ops.report import SECTIONS, ReportInput, WorkflowRun, title

LEFT_OUT = "The other sections are left out until the data validates."


@dataclass(frozen=True)
class Rendered:
    title: str
    markdown: str
    has_items: bool  # a section with items, or no focus this week (§7.4)


def _header(today: dt.date, run: WorkflowRun | None) -> list[str]:
    where = (
        f" in [workflow run #{run.number}]({run.url}); the dashboard is among its artifacts"
        if run
        else ""
    )
    return [f"# {title(today)}", "", f"Generated by portfolio-ops for {today} (UTC){where}."]


def render(data: ReportInput) -> Rendered:
    lines = _header(data.today, data.run)
    has_items = False
    for position in sorted(SECTIONS):
        part = SECTIONS[position](data)
        lines += ["", f"## {part.title}", "", *part.lines]
        has_items = has_items or part.has_items
    return Rendered(title(data.today), "\n".join(lines) + "\n", has_items)


def render_invalid(
    errors: Sequence[Diagnostic], prefix: str, today: dt.date, run: WorkflowRun | None = None
) -> Rendered:
    """Section 1 alone: the data does not validate, so nothing else can be trusted."""
    lines = _header(today, run)
    lines += ["", "## Validation errors", "", "```text"]
    lines += [error.render(prefix) for error in errors]
    lines += ["```", "", LEFT_OUT]
    return Rendered(title(today), "\n".join(lines) + "\n", True)
