"""V3: the overview — its pages, how they link each other, and what they must never let
through. Every name, date and number here is invented.
"""

from __future__ import annotations

import dataclasses
import datetime as dt
import re
from collections.abc import Callable
from dataclasses import replace

import pytest

from helpers import FIXTURES
from portfolio_ops.model import Account
from portfolio_ops.views.dashboard import DashboardInput
from portfolio_ops.views.overview import (
    GENERATED,
    PAGES,
    OverviewInput,
    chart_label,
    md,
    page_files,
    render_overview,
)
from scenarios import BUSY, SCANNED, WITH_REPOS

BuildView = Callable[..., DashboardInput]
Golden = Callable[[str, str], None]
CLOCKS = {"alpha": "2026-08-01", "epsilon": "2026-09-14"}


def overview(view: DashboardInput, **changes: object) -> OverviewInput:
    """The overview's input for the data of a dashboard's."""
    fields = {field.name: getattr(view, field.name) for field in dataclasses.fields(view)}
    return replace(OverviewInput(**fields), **changes)


def pages_match(golden: Golden, scenario: str, pages: dict[str, str]) -> None:
    """Each page equals golden/overview-<scenario>/<page>, where GitHub renders it too."""
    for name, text in pages.items():
        golden(f"overview-{scenario}/{name}", text)


def section(page: str, title: str) -> str:
    """The body of the level-2 section ``title`` of a page."""
    match = re.search(rf"^## {re.escape(title)}\n\n(.*?)(?=^## |\Z)", page, re.M | re.S)
    assert match is not None, title
    return match.group(1)


# ------------------------------------------------------------------ the pages


def test_a_quiet_portfolio_matches_its_golden_pages(view: BuildView, golden: Golden) -> None:
    data = overview(view(clocks={"alpha": "2026-09-15"}, today=dt.date(2026, 9, 20)))

    pages_match(golden, "quiet", render_overview(data))


def test_a_busy_portfolio_matches_its_golden_pages(view: BuildView, golden: Golden) -> None:
    pages_match(golden, "busy", render_overview(overview(view(BUSY, clocks=CLOCKS))))


def test_a_scanned_account_matches_its_golden_pages(view: BuildView, golden: Golden) -> None:
    data = overview(view(WITH_REPOS, clocks=CLOCKS), account=SCANNED)

    pages_match(golden, "account", render_overview(data))


def test_the_pages_are_registered_in_a_fixed_order_and_link_each_other(
    view: BuildView,
) -> None:
    pages = render_overview(overview(view()))

    assert sorted(PAGES) == [1, 2, 3, 4, 5]
    assert list(pages) == page_files()
    assert page_files() == [
        "README.md",
        "products.md",
        "repositories.md",
        "risks.md",
        "decisions.md",
    ]
    names = [PAGES[position].name for position in sorted(PAGES)]
    for current, (file, text) in zip(names, pages.items(), strict=True):
        nav = text.splitlines()[4]
        assert f"**{current}**" in nav, file
        for other, target in zip(names, page_files(), strict=True):
            if other != current:
                assert f"[{other}]({target})" in nav, (file, other)


def test_every_page_says_it_is_generated_and_by_what(view: BuildView) -> None:
    for text in render_overview(overview(view())).values():
        lines = text.splitlines()
        assert lines[0] == GENERATED
        assert lines[6].startswith("Generated by portfolio-ops for 2026-09-22 (UTC).")
        assert text.endswith("\n")
        assert not text.endswith("\n\n")


def test_what_needs_attention_is_listed_on_the_home_page(view: BuildView) -> None:
    home = render_overview(overview(view(BUSY, clocks=CLOCKS)))["README.md"]

    attention = section(home, "Needs attention")
    for marker in (
        "- **Stale:** Alpha (`alpha`), 52 days — the clock is past stale_days (30).",
        "- **Reviews overdue:** Beta (`beta`), due 2026-09-01.",
        (
            "- **Acceptances ended:** Two offline edits can overwrite each other "
            "(`core-data-loss`), accepted until 2026-09-01 — they count as open again."
        ),
        (
            "- **Open high or critical risks:** The first sync after an update can crash the "
            "app (`alpha-crash`), critical."
        ),
        (
            "- **Expired findings:** Syncs a change in under a second on a phone "
            "(`alpha-sync-claim`), held until 2026-09-01"
        ),
        "- **Copy-paste debt:** Epsilon (`epsilon`) carries a copy of Core (`core`).",
        (
            "- **No focus recorded this week.** Record one in decisions.md as "
            "`## 2026-09-22 · <product> · focus`."
        ),
    ):
        assert marker in attention, marker


def test_a_calm_portfolio_needs_no_attention(view: BuildView) -> None:
    calm = view(clocks={"alpha": "2026-09-15"}, today=dt.date(2026, 9, 20))

    home = render_overview(overview(calm))["README.md"]

    assert section(home, "Needs attention") == "Nothing needs attention.\n\n"


def test_without_history_the_pages_say_why_there_are_no_clocks(view: BuildView) -> None:
    pages = render_overview(overview(view(history=False)))

    reason = "The clocks are not shown: the data directory is not inside a git repository."
    assert reason in pages["README.md"]
    assert reason in pages["products.md"]
    assert "| Stale products | — (no clocks without the git history) |" in pages["README.md"]
    assert "| Data last committed | — |" in pages["README.md"]


def test_the_same_input_renders_the_same_bytes(view: BuildView) -> None:
    data = overview(view(WITH_REPOS, clocks=CLOCKS), account=SCANNED)

    assert render_overview(data) == render_overview(data)


# ------------------------------------------------------------------ escaping


EVIL = "Evil | <script>x</script> *bold* [link](https://example.invalid) $x$ ~~s~~ &amp;"
HOSTILE = {
    "products.yaml": f"""
        products:
          - id: alpha
            name: '{EVIL}'
            status: active
            next_action: 'Remove ![img](https://example.invalid/i.png) `code` # not a heading'
    """,
    "decisions.md": """
        # Decisions

        ## 2026-09-15 · alpha · focus
        # Not a heading
        - not a list
        1. not ordered
        ---
        <img src=x onerror=alert(1)>
        ```
        not code

        A second paragraph.
    """,
    "findings.yaml": "findings: []\n",
    "risks.yaml": "risks: []\n",
    "kernels.yaml": "kernels: []\n",
}


def unescaped(text: str, raw: str) -> bool:
    """Whether ``raw`` occurs in ``text`` without a backslash right before it."""
    return re.search(rf"(?<!\\){re.escape(raw)}", text) is not None


def test_every_value_from_the_data_is_escaped(view: BuildView) -> None:
    pages = render_overview(overview(view(HOSTILE)))
    text = "\n".join(pages.values())

    assert f"{md(EVIL)} (`alpha`)" in pages["products.md"]
    assert md(EVIL) == (
        "Evil \\| \\<script\\>x\\</script\\> \\*bold\\* \\[link\\](https://example.invalid) "
        "\\$x\\$ \\~\\~s\\~\\~ \\&amp;"
    )
    assert "Remove !\\[img\\](https://example.invalid/i.png) \\`code\\` \\# not a heading" in text
    for raw in ("<script>", "<img", "[link]", "[img]", "*bold*", "$x$", "~~s~~", "&amp;"):
        assert not unescaped(text, raw), raw


def test_a_decisions_text_keeps_its_lines_and_formats_nothing(view: BuildView) -> None:
    decisions = render_overview(overview(view(HOSTILE)))["decisions.md"]

    assert section(decisions, f"2026-09-15 · focus · {md(EVIL)} (`alpha`)") == (
        "> \\# Not a heading\\\n"
        "> \\- not a list\\\n"
        "> 1\\. not ordered\\\n"
        "> \\---\\\n"
        "> \\<img src=x onerror=alert(1)\\>\\\n"
        "> \\`\\`\\`\\\n"
        "> not code\n"
        ">\n"
        "> A second paragraph.\n"
    )


def test_a_table_cell_never_splits(view: BuildView) -> None:
    products = render_overview(overview(view(HOSTILE)))["products.md"]
    table = section(products, "Active").split("\n\n")[1].splitlines()

    columns = [len(re.split(r"(?<!\\)\|", row)) for row in table]
    assert len(set(columns)) == 1, table


@pytest.mark.parametrize(
    ("name", "label"),
    [
        ("Alpha", "Alpha"),
        ('Quote " colon : hash # semicolon ; percent %%', "Quote colon hash semicolon percent"),
        ("<br> <b>x</b> `code`", "br b x /b code"),
        ("section Paused\ntitle Other", "section Paused title Other"),
        ("Zażółć gęślą jaźń 🌿", "Zażółć gęślą jaźń"),
        ("a" * 60, "a" * 40),
        ("!!!", "fallback-id"),
        (None, "fallback-id"),
    ],
)
def test_a_chart_label_keeps_only_what_mermaid_cannot_misread(name: str | None, label: str) -> None:
    assert chart_label(name, "fallback-id") == label


# ------------------------------------------------------------------ charts


def mermaid(page: str) -> list[str]:
    """The Mermaid blocks of a page."""
    return re.findall(r"^```mermaid\n(.*?)^```$", page, re.M | re.S)


def test_the_home_page_shows_where_the_weeks_work_went(view: BuildView) -> None:
    home = render_overview(overview(view(WITH_REPOS), account=SCANNED))["README.md"]

    assert mermaid(home) == [
        (
            "pie showData\n"
            "    title Repositories with your activity since 2026-09-15\n"
            '    "Outside the portfolio" : 2\n'
            '    "Alpha" : 1\n'
            '    "Beta (paused)" : 1\n'
            '    "Ignored" : 1\n'
        )
    ]


def test_slices_that_would_share_a_label_take_their_ids(view: BuildView) -> None:
    # Epsilon, active like alpha, is renamed Alpha and lists side-quest.
    same = WITH_REPOS | {
        "products.yaml": WITH_REPOS["products.yaml"].replace(
            "            name: Epsilon\n",
            "            name: Alpha\n            repos: [example-owner/side-quest]\n",
        )
    }
    home = render_overview(overview(view(same), account=SCANNED))["README.md"]

    assert '    "Alpha alpha" : 1\n' in mermaid(home)[0]
    assert '    "Alpha epsilon" : 1\n' in mermaid(home)[0]


def test_without_a_scan_there_is_no_pie(view: BuildView) -> None:
    home = render_overview(overview(view()))["README.md"]

    assert mermaid(home) == []
    assert section(home, "Where the work went").startswith(
        "The account was not scanned: PORTFOLIO\\_ACCOUNT\\_TOKEN is not set"
    )


def test_the_review_dates_are_on_a_timeline_and_an_overdue_one_is_critical(
    view: BuildView,
) -> None:
    products = render_overview(overview(view(BUSY)))["products.md"]

    assert mermaid(products) == [
        (
            "gantt\n"
            "    title Review dates\n"
            "    dateFormat YYYY-MM-DD\n"
            "    axisFormat %Y-%m-%d\n"
            "    todayMarker off\n"
            "    Today : active, milestone, 2026-09-22, 0d\n"
            "    section Paused\n"
            "    Review of Beta : crit, milestone, 2026-09-01, 0d\n"
            "    section Dormant\n"
            "    Review of Gamma : milestone, 2026-12-01, 0d\n"
        )
    ]


# ------------------------------------------------------------------ the account (§7.12)


def test_the_repositories_page_puts_the_weeks_work_first(view: BuildView) -> None:
    page = render_overview(overview(view(WITH_REPOS), account=SCANNED))["repositories.md"]

    week = section(page, "Worked on this week")
    rows = [line for line in week.splitlines() if line.startswith("| [")]
    assert [re.search(r"\[`([^`]+)`\]", row)[1] for row in rows] == [  # type: ignore[index]
        "example-owner/alpha",
        "example-owner/side-quest",
        "example-owner/beta",
        "example-owner/weekend-jam",
        "example-owner/dotfiles",
    ]
    assert "| **outside the portfolio** | 2026-09-20 |" in week
    assert "| Beta (`beta`), **paused** | 2026-09-18 |" in week
    assert "| **outside the portfolio** | 2026-09-17, a push by anyone |" in week
    assert "| ignored | 2026-09-16 |" in week
    every = section(page, "All repositories")
    assert "<summary>Forks and archived repositories (2)</summary>" in every
    assert every.index("example-owner/core") < every.index("<details>")
    assert every.index("example-owner/old-fork") > every.index("<details>")
    assert "| [`example-owner/core`](https://github.com/example-owner/core) · private |" in every
    assert section(page, "Listed but not found").endswith(
        "| `example-owner/gamma-renamed` | Gamma (`gamma`) |\n"
    )


def test_repositories_link_to_the_server_the_account_is_on(view: BuildView) -> None:
    data = overview(view(WITH_REPOS), account=SCANNED, server="https://git.example.invalid/")

    page = render_overview(data)["repositories.md"]

    assert "(https://git.example.invalid/example-owner/alpha)" in page
    assert "https://github.com" not in page


def test_with_allow_public_no_private_repository_is_named(view: BuildView) -> None:
    hidden = replace(SCANNED.scan, hide_private=True) if SCANNED.scan else None

    text = "\n".join(
        render_overview(overview(view(WITH_REPOS), account=Account(scan=hidden))).values()
    )

    for name in ("side-quest", "weekend-jam", "dotfiles", "bot-only"):
        assert name not in text, name
    assert "allow_public is set, so private repositories are left out." in text


def test_a_token_that_sees_only_public_repositories_needs_attention(view: BuildView) -> None:
    scan = (
        replace(SCANNED.scan, sees_private=False, left_out="example-owner/data")
        if SCANNED.scan
        else None
    )
    pages = render_overview(overview(view(WITH_REPOS), account=Account(scan=scan)))

    blind = (
        "**The token sees only public repositories:** the token does not list this private "
        "repository, example-owner/data, so every private repository of the account is missing"
    )
    assert f"- {blind}" in section(pages["README.md"], "Needs attention")
    assert pages["repositories.md"].count(blind) == 1
    assert ", **public repositories only** |" in pages["README.md"]


def test_a_failed_scan_needs_attention(view: BuildView) -> None:
    failed = Account(problem="GitHub rejected it — replace it", failed=True)

    pages = render_overview(overview(view(), account=failed))

    home = pages["README.md"]
    assert "- **The account was not scanned.** GitHub rejected it — replace it." in home
    assert "| [Repositories worked on](repositories.md) | **the scan failed** |" in home
    assert pages["repositories.md"].count("The account was not scanned: GitHub rejected it") == 1


def test_without_a_scan_the_repositories_page_lists_the_portfolios(view: BuildView) -> None:
    page = render_overview(overview(view(WITH_REPOS)))["repositories.md"]

    assert section(page, "Listed in the portfolio") == (
        "| Repository | Listed by |\n"
        "|---|---|\n"
        "| [`example-owner/alpha`](https://github.com/example-owner/alpha) | Alpha (`alpha`) |\n"
        "| [`example-owner/beta`](https://github.com/example-owner/beta) | Beta (`beta`) |\n"
        "| [`example-owner/core`](https://github.com/example-owner/core) | Core (`core`) |\n"
        "| [`example-owner/gamma-renamed`](https://github.com/example-owner/gamma-renamed) "
        "| Gamma (`gamma`) |\n"
    )


# ------------------------------------------------------------------ decisions


def test_every_decision_is_on_its_page_newest_first_and_the_latest_on_the_home_page(
    view: BuildView,
) -> None:
    notes = "".join(
        f"## 2026-10-{day:02} · alpha · external\nNote {day}.\n" for day in range(1, 13)
    )
    decisions = (FIXTURES / "valid" / "decisions.md").read_text() + notes
    pages = render_overview(
        overview(view({"decisions.md": decisions}, today=dt.date(2026, 10, 15)))
    )

    assert "All 15 decisions, newest first." in pages["decisions.md"]
    assert re.findall(r"^> Note (\d+)\.$", pages["decisions.md"], re.M) == [
        str(day) for day in range(12, 0, -1)
    ]
    latest = section(pages["README.md"], "Latest decisions")
    assert re.findall(r"^- 2026-10-(\d+) · external", latest, re.M) == [
        "12",
        "11",
        "10",
        "09",
        "08",
    ]
    assert "[Decisions](decisions.md)" in latest
