"""V1: the dashboard — the whole portfolio on one static HTML page (spec §6).

The page is one self-contained file. Its stylesheet is inline, and it has no script, font,
image or link out, so it works as a workflow artifact or a local file and fetches nothing;
its Content-Security-Policy allows exactly its own stylesheet. Every value from the data
is escaped. A data repository is private (§8.8) and the page says so: it is kept as a
workflow artifact or a local file, never published on GitHub Pages.

Panels are registered functions in a fixed order, like the report's sections (P10). The
page depends on nothing but its input: with ``--today`` fixed, the same data renders the
same bytes, which is what the golden files in the tests pin down.
"""

from __future__ import annotations

import base64
import datetime as dt
import hashlib
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass
from functools import cache
from html import escape
from importlib import resources

from portfolio_ops.history import Clock
from portfolio_ops.model import (
    DECISIONS_FILE,
    PORTFOLIO,
    SEVERITIES,
    Decision,
    Portfolio,
    Product,
    Risk,
    Term,
)
from portfolio_ops.report.sections import this_weeks_focus
from portfolio_ops.rules.kernels import consumers, copies, kernel_state
from portfolio_ops.views import latest_about, newest_first

DECISIONS_SHOWN = 10
PRIVATE_NOTE = (
    "<strong>Private.</strong> This page lists the portfolio's weak spots: its risks, "
    "rejections and stalled projects. Keep it a workflow artifact or a local file, and never "
    "publish it on GitHub Pages."
)


@dataclass(frozen=True)
class DashboardInput:
    portfolio: Portfolio
    today: dt.date
    clocks: Mapping[str, Clock] | None  # N1 for every active product; None without history
    last_data_commit: dt.date | None
    no_clocks: str = ""  # why there is no history to read the clocks from


@dataclass(frozen=True)
class Panel:
    anchor: str  # the id of the panel's section, which the navigation links to
    title: str
    body: str  # HTML, every value from the data escaped
    count: int | None = None  # shown next to the title


PanelFunction = Callable[[DashboardInput], Panel]

PANELS: dict[int, PanelFunction] = {}


def panel(position: int) -> Callable[[PanelFunction], PanelFunction]:
    """Register a dashboard panel at its position on the page."""

    def register(function: PanelFunction) -> PanelFunction:
        if position in PANELS:
            raise ValueError(f"dashboard position {position} is registered twice")
        PANELS[position] = function
        return function

    return register


# --------------------------------------------------------------------------- the page


@cache
def style() -> tuple[str, str]:
    """The stylesheet as the page embeds it, and its hash for the Content-Security-Policy."""
    css = resources.files("portfolio_ops.views").joinpath("dashboard.css").read_text("utf-8")
    text = "\n" + css
    digest = base64.b64encode(hashlib.sha256(text.encode("utf-8")).digest()).decode("ascii")
    return text, f"sha256-{digest}"


def render_dashboard(view: DashboardInput) -> str:
    panels = [PANELS[position](view) for position in sorted(PANELS)]
    css, digest = style()
    policy = f"default-src 'none'; style-src '{digest}'; base-uri 'none'; form-action 'none'"
    links = "".join(f'<li><a href="#{p.anchor}">{_e(p.title)}</a></li>' for p in panels)
    lines = [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<meta name="robots" content="noindex, nofollow">',
        f'<meta http-equiv="Content-Security-Policy" content="{policy}">',
        f"<title>Portfolio dashboard — {view.today}</title>",
        f"<style>{css}</style>",
        "</head>",
        "<body>",
        "<header>",
        "<h1>Portfolio dashboard</h1>",
        (
            f'<p class="lede">Generated by portfolio-ops for {view.today} (UTC). It shows the '
            "state of the data files and decides nothing: the rules run in validate, the "
            "weekly report and the gates.</p>"
        ),
        f'<p class="private" role="note">{PRIVATE_NOTE}</p>',
        f'<nav aria-label="Panels"><ul>{links}</ul></nav>',
        "</header>",
        "<main>",
        *(_section(p) for p in panels),
        "</main>",
        f"<footer><p>{_footer(view)}</p></footer>",
        "</body>",
        "</html>",
    ]
    return "\n".join(lines) + "\n"


def _section(p: Panel) -> str:
    count = "" if p.count is None else f' <span class="count">{p.count}</span>'
    return (
        f'<section id="{p.anchor}" aria-labelledby="{p.anchor}-title">\n'
        f'<h2 id="{p.anchor}-title">{_e(p.title)}{count}</h2>\n{p.body}\n</section>'
    )


def _footer(view: DashboardInput) -> str:
    if view.clocks is None:
        return "The git history was not read, so the page shows no clocks."
    if view.last_data_commit is None:
        return "No commit touches the data yet."
    return f"The data was last committed on {_date(view.last_data_commit)}."


# --------------------------------------------------------------------------- HTML helpers


def _e(value: object) -> str:
    return escape(str(value), quote=True)


def _code(value: str) -> str:
    return f"<code>{_e(value)}</code>"


def label(name: str | None, ident: str) -> str:
    """``Name <code>id</code>``, or just the id when there is no other name."""
    if not name or name == ident:
        return _code(ident)
    return f"{_e(name)} {_code(ident)}"


def _entity(portfolio: Portfolio, ident: str | None) -> str:
    """A product or a kernel by its name, the portfolio, or any other id as it is — a risk's
    scope, a finding's subject, an id in a decision heading."""
    if ident is None or ident == PORTFOLIO:
        return "the portfolio"
    product = portfolio.product(ident)
    if product is not None:
        return label(product.name, ident)
    kernel = portfolio.kernel(ident)
    return label(kernel.name if kernel else None, ident)


def _badge(text: str, tone: str = "") -> str:
    kind = f"badge {tone}" if tone else "badge"
    return f'<span class="{kind}">{_e(text)}</span>'


def _sub(html: str) -> str:
    return f'<span class="sub">{html}</span>'


def _terms(terms: Iterable[Term] | None) -> str:
    values = [_e(term.value) for term in terms or ()]
    return ", ".join(values) if values else "—"


def _stacked(items: Sequence[str]) -> str:
    return "<br>".join(items) if items else "—"


def _date(value: dt.date | None) -> str:
    return "—" if value is None else f'<time datetime="{value}">{value}</time>'


def _days(count: int) -> str:
    return "1 day" if count == 1 else f"{count} days"


def _table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> str:
    head = "".join(f'<th scope="col">{_e(h)}</th>' for h in headers)
    body = ["<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>" for row in rows]
    return "\n".join(
        [
            '<div class="table"><table>',
            f"<thead><tr>{head}</tr></thead>",
            "<tbody>",
            *body,
            "</tbody>",
            "</table></div>",
        ]
    )


def _empty(text: str) -> str:
    return f'<p class="empty">{_e(text)}</p>'


def _decision_ref(decision: Decision | None) -> str:
    if decision is None:
        return "—"
    return f"{_date(decision.date)} · {_e(decision.type)}"


def _products(portfolio: Portfolio, *statuses: str) -> list[Product]:
    return [p for p in portfolio.products if p.status in statuses and p.id is not None]


# --------------------------------------------------------------------------- panels


def _tile(name: str, value: str, note: str, *, attention: bool = False) -> str:
    kind = "tile attention" if attention else "tile"
    return (
        f'<div class="{kind}"><dt>{_e(name)}</dt><dd class="value">{value}</dd>'
        f'<dd class="note">{note}</dd></div>'
    )


def _counted(count: int, noun: str) -> str:
    return f"{count} {noun}" if count == 1 else f"{count} {noun}s"


@panel(1)
def summary(view: DashboardInput) -> Panel:
    """The numbers at a glance. A tile stands out when what it counts needs the owner: an
    item of the weekly report, a risk that fails a gate (B2) or a finding that has expired."""
    portfolio, today = view.portfolio, view.today
    thresholds = portfolio.config.thresholds
    tiles = [
        _tile(
            "Active",
            f"{len(_products(portfolio, 'active'))} of {thresholds.wip_limit}",
            "active products within wip_limit",
        )
    ]
    if view.clocks is None:
        tiles.append(_tile("Stale", "—", "no clocks without the git history"))
    else:
        stale = sum(1 for clock in view.clocks.values() if clock.days > thresholds.stale_days)
        note = f"clock past stale_days ({thresholds.stale_days})"
        tiles.append(_tile("Stale", str(stale), note, attention=stale > 0))
    focus = this_weeks_focus(portfolio, today)
    if focus is None:
        tiles.append(_tile("Focus this week", "None", "record a focus decision", attention=True))
    else:
        product = portfolio.product(focus.ids[0])
        name = product.name if product and product.name else focus.ids[0]
        tiles.append(_tile("Focus this week", _e(name), f"recorded {_date(focus.date)}"))
    ideas = len(_products(portfolio, "idea"))
    tiles.append(_tile("Ideas", str(ideas), "not yet through the idea gate"))
    waiting = _products(portfolio, "paused", "dormant")
    overdue = sum(1 for p in waiting if p.review_by is not None and p.review_by < today)
    tiles.append(
        _tile(
            "Paused or dormant",
            str(len(waiting)),
            f"{_counted(overdue, 'review')} overdue" if overdue else "no review overdue",
            attention=overdue > 0,
        )
    )
    open_risks = [risk for risk in portfolio.risks if risk.counts_as_open(today)]
    severe = sum(1 for risk in open_risks if risk.severity in ("high", "critical"))
    lapsed = sum(1 for risk in open_risks if risk.state == "accepted")
    notes = [f"{severe} high or critical" if severe else "none high or critical"]
    if lapsed:
        notes.append(f"{_counted(lapsed, 'acceptance')} ended")
    tiles.append(
        _tile(
            "Open risks", str(len(open_risks)), " · ".join(notes), attention=bool(severe or lapsed)
        )
    )
    config = portfolio.config
    expired = sum(
        1
        for finding in portfolio.findings
        if (until := config.expiry(finding)) is not None and until < today
    )
    tiles.append(
        _tile(
            "Expired findings",
            str(expired),
            f"of {_counted(len(portfolio.findings), 'finding')}",
            attention=expired > 0,
        )
    )
    debt = len(copies(portfolio))
    tiles.append(
        _tile("Copy-paste debt", str(debt), "kernel copies in products", attention=debt > 0)
    )
    states = [kernel_state(portfolio, kernel).state for kernel in portfolio.kernels]
    by_state = " · ".join(f"{states.count(s)} {s}" for s in ("done", "extracted", "planned"))
    tiles.append(_tile("Kernels", str(len(states)), by_state if states else "none registered"))
    body = '<dl class="tiles">\n' + "\n".join(tiles) + "\n</dl>"
    return Panel("summary", "Summary", body)


@panel(2)
def active(view: DashboardInput) -> Panel:
    """The products in progress: next action, clock (N1, stale per N2), capabilities, kernels."""
    portfolio = view.portfolio
    stale_days = portfolio.config.thresholds.stale_days
    focus = this_weeks_focus(portfolio, view.today)
    products = _products(portfolio, "active")
    rows = []
    for product in products:
        pid = product.id or ""
        name = label(product.name, pid)
        if focus is not None and focus.ids[0] == pid:
            name += " " + _badge("focus", "focus")
        rows.append(
            (
                name,
                _e(product.next_action or "—"),
                _clock(view, pid, stale_days),
                _terms(product.capabilities),
                _feeds(portfolio, product),
            )
        )
    parts = []
    if view.clocks is None:
        parts.append(f'<p class="note">The clocks are not shown: {_e(view.no_clocks)}.</p>')
    if rows:
        headers = ("Product", "Next action", "Clock", "Capabilities", "Kernels")
        parts.append(_table(headers, rows))
    else:
        parts.append(_empty("No product is active."))
    return Panel("active", "Active products", "\n".join(parts), len(products))


def _clock(view: DashboardInput, product_id: str, stale_days: int) -> str:
    clock = view.clocks.get(product_id) if view.clocks is not None else None
    if clock is None:
        return "—"
    stale = " " + _badge("stale", "attention") if clock.days > stale_days else ""
    return f"{_days(clock.days)}{stale}{_sub(f'since {_date(clock.since)}')}"


def _feeds(portfolio: Portfolio, product: Product) -> str:
    items = []
    for feed in product.feeds_from:
        kernel = portfolio.kernel(feed.kernel or "")
        name = label(kernel.name if kernel else None, feed.kernel or "")
        mode = feed.mode or ""
        items.append(f"{name} {_badge(mode, 'attention' if mode == 'copy' else '')}")
    return _stacked(items)


@panel(3)
def ideas(view: DashboardInput) -> Panel:
    portfolio = view.portfolio
    products = _products(portfolio, "idea")
    rows = [
        (
            label(p.name, p.id or ""),
            _terms(p.capabilities),
            _decision_ref(latest_about(portfolio, p.id or "")),
        )
        for p in products
    ]
    body = (
        _table(("Idea", "Capabilities", "Latest decision"), rows)
        if rows
        else _empty("No idea is registered.")
    )
    return Panel("ideas", "Ideas", body, len(products))


@panel(4)
def paused_and_dormant(view: DashboardInput) -> Panel:
    """Products that wait for a review, the soonest first; an overdue review stands out (N4)."""
    products = sorted(
        _products(view.portfolio, "paused", "dormant"),
        key=lambda p: (p.review_by or dt.date.max, p.id or ""),
    )
    rows = [
        (
            label(p.name, p.id or ""),
            _e(p.status),
            _e(p.status_reason or "—"),
            _review(p.review_by, view.today),
            _e(p.next_action or "—"),
        )
        for p in products
    ]
    headers = ("Product", "Status", "Reason", "Review by", "Next action")
    body = _table(headers, rows) if rows else _empty("No product is paused or dormant.")
    return Panel("waiting", "Paused and dormant", body, len(products))


def _review(review_by: dt.date | None, today: dt.date) -> str:
    if review_by is None:
        return "—"
    days = (review_by - today).days
    if days < 0:
        return f"{_date(review_by)} {_badge('overdue', 'attention')}{_sub(f'{_days(-days)} ago')}"
    return f"{_date(review_by)}{_sub('today' if days == 0 else f'in {_days(days)}')}"


@panel(5)
def archived(view: DashboardInput) -> Panel:
    portfolio = view.portfolio
    products = _products(portfolio, "archived")
    rows = [
        (label(p.name, p.id or ""), _decision_ref(latest_about(portfolio, p.id or "")))
        for p in products
    ]
    body = (
        _table(("Product", "Latest decision"), rows) if rows else _empty("No product is archived.")
    )
    return Panel("archived", "Archived", body, len(products))


_KERNEL_TONES = {"done": "success", "extracted": "info", "planned": ""}


@panel(6)
def kernels(view: DashboardInput) -> Panel:
    """Each kernel's state (K1) and who uses it how; a copy is copy-paste debt (K2)."""
    portfolio = view.portfolio
    rows = []
    for kernel in portfolio.kernels:
        kid = kernel.id or ""
        state = kernel_state(portfolio, kernel)
        rows.append(
            (
                label(kernel.name, kid),
                _terms(kernel.capabilities),
                f"{_badge(state.state, _KERNEL_TONES[state.state])}{_sub(_e(state.progress))}",
                *(
                    _stacked([label(p.name, p.id or "") for p in consumers(portfolio, kid, mode)])
                    for mode in ("package", "copy", "planned")
                ),
            )
        )
    headers = ("Kernel", "Capabilities", "State", "As a package", "As a copy", "Planned")
    body = _table(headers, rows) if rows else _empty("No kernel is registered.")
    return Panel("kernels", "Kernels", body, len(rows))


_SEVERITY_TONES = {"critical": "danger", "high": "danger", "medium": "attention", "low": ""}


@panel(7)
def risks(view: DashboardInput) -> Panel:
    """Every risk: the ones that count as open first (B3), then accepted, then closed."""
    portfolio, today = view.portfolio, view.today

    def order(risk: Risk) -> tuple[int, int, str]:
        group = 0 if risk.counts_as_open(today) else 1 if risk.state == "accepted" else 2
        severity = SEVERITIES.index(risk.severity) if risk.severity in SEVERITIES else 0
        return group, -severity, risk.id or ""

    rows = [
        (
            label(risk.title, risk.id or ""),
            _entity(portfolio, risk.scope),
            _badge(risk.severity or "", _SEVERITY_TONES.get(risk.severity or "", "")),
            _terms(risk.applies_to),
            _risk_state(risk, today),
        )
        for risk in sorted(portfolio.risks, key=order)
    ]
    headers = ("Risk", "Scope", "Severity", "Applies to", "State")
    body = _table(headers, rows) if rows else _empty("No risk is registered.")
    return Panel("risks", "Risks", body, len(rows))


def _risk_state(risk: Risk, today: dt.date) -> str:
    if risk.state == "accepted":
        if risk.acceptance_holds(today):
            return f"{_badge('accepted', 'info')}{_sub(f'until {_date(risk.accepted_until)}')}"
        ended = f"held until {_date(risk.accepted_until)}; counts as open"
        return f"{_badge('acceptance ended', 'attention')}{_sub(ended)}"
    return _badge(risk.state or "", "attention" if risk.state == "open" else "")


@panel(8)
def findings(view: DashboardInput) -> Panel:
    """What was verified and until when it holds (P2), the soonest to expire first."""
    portfolio, today = view.portfolio, view.today
    config = portfolio.config
    dated = sorted(
        ((config.expiry(f), f) for f in portfolio.findings),
        key=lambda pair: (pair[0] or dt.date.max, pair[1].id or ""),
    )
    rows = []
    for until, finding in dated:
        what = _e(finding.result or "") + _sub(_code(finding.id or ""))
        if finding.evidence:
            what += _sub(f"Evidence: {_e(finding.evidence)}")
        holds = _date(until)
        if until is not None and until < today:
            holds += " " + _badge("expired", "attention")
        rows.append(
            (
                what,
                _entity(portfolio, finding.subject),
                _e(finding.type or ""),
                _date(finding.checked_on),
                holds,
                _terms(finding.used_in),
            )
        )
    headers = ("Finding", "Subject", "Type", "Checked on", "Holds until", "Used in")
    body = _table(headers, rows) if rows else _empty("No finding is recorded.")
    return Panel("findings", "Findings", body, len(rows))


@panel(9)
def capabilities(view: DashboardInput) -> Panel:
    """Which products and kernels have each capability: duplication shows by purpose (§8.6)."""
    portfolio = view.portfolio
    vocabulary = portfolio.config.declared("capabilities")
    rows = []
    for capability in vocabulary:
        products = [
            f'{label(p.name, p.id or "")} <span class="note">{_e(p.status)}</span>'
            for p in portfolio.products
            if p.status != "archived" and _has(p.capabilities, capability)
        ]
        kernels = [
            label(k.name, k.id or "") for k in portfolio.kernels if _has(k.capabilities, capability)
        ]
        rows.append((_e(capability), _stacked(products), _stacked(kernels)))
    body = (
        _table(("Capability", "Products", "Kernels"), rows)
        if rows
        else _empty("No capability is declared in config.yaml.")
    )
    return Panel("capabilities", "Capabilities", body, len(rows))


def _has(terms: Iterable[Term] | None, value: str) -> bool:
    return any(term.value == value for term in terms or ())


@panel(10)
def decisions(view: DashboardInput) -> Panel:
    """The latest decisions with their text, newest first."""
    portfolio = view.portfolio
    every = newest_first(portfolio)
    shown = every[:DECISIONS_SHOWN]
    if not every:
        return Panel("decisions", "Latest decisions", _empty("No decision is recorded yet."), 0)
    if len(shown) < len(every):
        intro = (
            f"The {len(shown)} latest of {len(every)} decisions, newest first; the others are "
            f"in {DECISIONS_FILE}."
        )
    else:
        intro = (
            "The only decision."
            if len(every) == 1
            else f"All {len(every)} decisions, newest first."
        )
    parts = [f'<p class="note">{_e(intro)}</p>']
    for decision in shown:
        names = ", ".join(_entity(portfolio, ident) for ident in decision.ids)
        heading = f"<h3>{_date(decision.date)} · {_e(decision.type)} · {names}</h3>"
        text = f'\n<p class="text">{_e(decision.text)}</p>' if decision.text else ""
        parts.append(f'<article class="decision">\n{heading}{text}\n</article>')
    return Panel("decisions", "Latest decisions", "\n".join(parts), len(every))
