"""V3: the overview — the whole portfolio as Markdown pages in the data repository.

GitHub renders Markdown files with tables, links between pages, collapsible sections and
Mermaid charts, and shows them to exactly the people who can read the repository (spec
§7.11, §8.10, ADR 0009). The workflow commits the pages to ``overview/`` of the private
data repository, where they open on the web and in GitHub's mobile app.

A view like the dashboard: it reads the validated portfolio and the values the rules
already derive, and decides nothing. Pages are registered functions in a fixed order, like
the report's sections (P10). Every value from the data is escaped; a Mermaid label keeps
only letters, digits, spaces and a few safe marks; and with ``allow_public`` no private
repository is named. With ``--today`` fixed, the same input renders the same bytes.
"""

from __future__ import annotations

import datetime as dt
import re
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass

from portfolio_ops.history import Clock
from portfolio_ops.model import (
    DECISIONS_FILE,
    NOT_SCANNED,
    PORTFOLIO,
    SEVERITIES,
    Account,
    AccountRepository,
    AccountScan,
    Decision,
    Finding,
    Kernel,
    Portfolio,
    Product,
    Risk,
    Term,
    is_repository,
)
from portfolio_ops.report.sections import escape, this_weeks_focus
from portfolio_ops.rules.account import (
    blind_spot,
    ignored,
    inactive_work,
    listing,
    outside_portfolio,
    shown,
    unknown_repositories,
    visibility,
    worked_on,
)
from portfolio_ops.rules.kernels import consumers, copies, kernel_state
from portfolio_ops.views import latest_about, newest_first

# The first line of every page. It is how ``overview`` tells its own pages from a file it
# must not overwrite, such as the owner's README.
GENERATED = (
    "<!-- Generated by portfolio-ops. The workflow rewrites this page from the data files, "
    "so edit those instead. -->"
)
GENERATED_PREFIX = "<!-- Generated by portfolio-ops"
DEFAULT_SERVER = "https://github.com"
LATEST_DECISIONS = 5  # on the home page; decisions.md has them all
CHART_LABEL_LENGTH = 40
SEVERE = ("high", "critical")


@dataclass(frozen=True)
class OverviewInput:
    portfolio: Portfolio
    today: dt.date
    clocks: Mapping[str, Clock] | None  # N1 for every active product; None without history
    last_data_commit: dt.date | None
    no_clocks: str = ""  # why there is no history to read the clocks from
    account: Account = NOT_SCANNED  # the account scan (§7.12), or why there is none
    server: str = DEFAULT_SERVER  # the GitHub the account's repositories are linked on


PageBody = Callable[[OverviewInput], list[str]]


@dataclass(frozen=True)
class Page:
    file: str
    title: str  # the page's heading
    name: str  # the page in the navigation line
    body: PageBody  # Markdown lines, every value from the data escaped


PAGES: dict[int, Page] = {}


def page(position: int, file: str, title: str, name: str) -> Callable[[PageBody], PageBody]:
    """Register an overview page at its position in the navigation."""

    def register(body: PageBody) -> PageBody:
        if position in PAGES:
            raise ValueError(f"overview position {position} is registered twice")
        PAGES[position] = Page(file, title, name, body)
        return body

    return register


def page_files() -> list[str]:
    """The file name of every page, in the order of the navigation."""
    return [PAGES[position].file for position in sorted(PAGES)]


def render_overview(view: OverviewInput) -> dict[str, str]:
    """Every page by its file name, in the order of the navigation."""
    pages = [PAGES[position] for position in sorted(PAGES)]
    rendered = {}
    for current in pages:
        nav = " · ".join(
            f"**{other.name}**" if other is current else f"[{other.name}]({other.file})"
            for other in pages
        )
        lines = [
            GENERATED,
            "",
            f"# {current.title}",
            "",
            nav,
            "",
            (
                f"Generated by portfolio-ops for {view.today} (UTC). These pages show the state "
                "of the data files and decide nothing: the rules run in validate, the weekly "
                "report and the gates."
            ),
            "",
            *current.body(view),
        ]
        rendered[current.file] = "\n".join(lines).rstrip("\n") + "\n"
    return rendered


# --------------------------------------------------------------------------- Markdown

_MORE = re.compile(r"([~$&])")  # strikethrough, math and character references
_BLOCK = re.compile(r"^(?:([-+=])|(\d{1,9})([.)]))")  # what starts a list or a heading


def md(text: str | None) -> str:
    """A value from the data as inline Markdown on one line: nothing in it formats, links,
    or starts math, strikethrough or an HTML entity."""
    return _MORE.sub(r"\\\1", escape(text or ""))


def chart_label(text: str | None, fallback: str) -> str:
    """Text that Mermaid cannot misread: letters, digits, spaces and ``. - _ /``, on one
    line and at most 40 characters — or the fallback, an id, when nothing is left."""
    kept = "".join(c if c.isalnum() or c in " .-_/" else " " for c in text or "")
    label = " ".join(kept.split())[:CHART_LABEL_LENGTH].strip()
    return label or fallback


def label(name: str | None, ident: str) -> str:
    """``Name (`id`)``, or the id alone when there is no other name."""
    if not name or name == ident:
        return f"`{ident}`"
    return f"{md(name)} (`{ident}`)"


def _entity(portfolio: Portfolio, ident: str | None) -> str:
    """A product, a kernel or a risk by its name, the portfolio, or any other id as it is —
    a risk's scope, a finding's subject, an id in a decision heading."""
    if ident is None or ident == PORTFOLIO:
        return "the portfolio"
    product = portfolio.product(ident)
    if product is not None:
        return label(product.name, ident)
    kernel = portfolio.kernel(ident)
    if kernel is not None:
        return label(kernel.name, ident)
    risk = next((r for r in portfolio.risks if r.id == ident), None)
    return label(risk.title if risk else None, ident)


def _repository(view: OverviewInput, name: str, *, link: bool = True) -> str:
    """A repository as code, linked to it on GitHub."""
    if not is_repository(name):
        return md(name)
    return f"[`{name}`]({view.server.rstrip('/')}/{name})" if link else f"`{name}`"


def _section(title: str, lines: Sequence[str]) -> list[str]:
    return [f"## {title}", "", *lines, ""]


def _table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    return [
        f"| {' | '.join(headers)} |",
        f"|{'|'.join('---' for _ in headers)}|",
        *(f"| {' | '.join(row)} |" for row in rows),
    ]


def _quoted(text: str) -> list[str]:
    """A decision's text as a block quote: every line escaped, its line breaks kept."""
    lines = text.split("\n")
    quoted = []
    for index, line in enumerate(lines):
        if not line.strip():
            quoted.append(">")
            continue
        escaped = _BLOCK.sub(
            lambda m: f"\\{m[1]}" if m[1] else f"{m[2]}\\{m[3]}",
            md(line),
        )
        follows = index + 1 < len(lines) and lines[index + 1].strip()
        quoted.append(f"> {escaped}\\" if follows else f"> {escaped}")
    return quoted


def _terms(terms: Iterable[Term] | None) -> str:
    values = [md(term.value) for term in terms or ()]
    return ", ".join(values) if values else "—"


def _joined(items: Sequence[str], empty: str = "—") -> str:
    return "; ".join(items) if items else empty


def _paragraphs(texts: Sequence[str]) -> list[str]:
    """Texts as paragraphs, a blank line between each two."""
    lines: list[str] = []
    for text in texts:
        lines += [text, ""]
    return lines[:-1]


def _days(count: int) -> str:
    return "1 day" if count == 1 else f"{count} days"


def _count(number: int, noun: str) -> str:
    plural = f"{noun[:-1]}ies" if noun.endswith("y") else f"{noun}s"
    return f"{number} {noun}" if number == 1 else f"{number} {plural}"


def _date(value: dt.date | None) -> str:
    return "—" if value is None else str(value)


# --------------------------------------------------------------------------- the portfolio


def _products(portfolio: Portfolio, *statuses: str) -> list[Product]:
    return [p for p in portfolio.products if p.status in statuses and p.id is not None]


def _stale(view: OverviewInput) -> list[tuple[Product, Clock]]:
    """The active products whose clock is past stale_days (N2), the oldest first."""
    if view.clocks is None:
        return []
    limit = view.portfolio.config.thresholds.stale_days
    found = []
    for product_id, clock in view.clocks.items():
        product = view.portfolio.product(product_id)
        if product is not None and clock.days > limit:
            found.append((product, clock))
    return sorted(found, key=lambda pair: (-pair[1].days, pair[0].id or ""))


def _overdue(view: OverviewInput) -> list[Product]:
    """Paused and dormant products whose review is overdue (N4), the longest overdue first."""
    return sorted(
        (
            p
            for p in _products(view.portfolio, "paused", "dormant")
            if p.review_by is not None and p.review_by < view.today
        ),
        key=lambda p: (p.review_by, p.id or ""),
    )


def _ended(view: OverviewInput) -> list[Risk]:
    """Accepted risks whose acceptance has ended: they count as open again (B3)."""
    return [
        risk
        for risk in view.portfolio.risks
        if risk.state == "accepted" and not risk.acceptance_holds(view.today)
    ]


def _severity(risk: Risk) -> int:
    return SEVERITIES.index(risk.severity) if risk.severity in SEVERITIES else 0


def _expired(view: OverviewInput) -> list[tuple[dt.date, Finding]]:
    """Findings past their expiry (P2), the longest expired first."""
    config = view.portfolio.config
    found = [
        (until, finding)
        for finding in view.portfolio.findings
        if (until := config.expiry(finding)) is not None and until < view.today
    ]
    return sorted(found, key=lambda pair: (pair[0], pair[1].id or ""))


def _clock(view: OverviewInput, product_id: str) -> str:
    clock = view.clocks.get(product_id) if view.clocks is not None else None
    if clock is None:
        return "—"
    text = f"{_days(clock.days)} since {clock.since}"
    stale = clock.days > view.portfolio.config.thresholds.stale_days
    return f"{text}, **stale**" if stale else text


def _feeds(view: OverviewInput, product: Product) -> str:
    items = []
    for feed in product.feeds_from:
        kernel = view.portfolio.kernel(feed.kernel or "")
        mode = f"**{feed.mode}**" if feed.mode == "copy" else md(feed.mode)
        items.append(f"{label(kernel.name if kernel else None, feed.kernel or '')}, {mode}")
    return _joined(items)


def _listed(view: OverviewInput, owner: Product | Kernel) -> str:
    return ", ".join(_repository(view, term.value) for term in owner.repos) or "—"


def _decision_ref(decision: Decision | None) -> str:
    return "—" if decision is None else f"{decision.date} · {md(decision.type)}"


def _last_push(scan: AccountScan, owner: Product | Kernel) -> str:
    """The latest push to the repositories a product or a kernel lists."""
    by_name = {r.name.lower(): r for r in scan.repositories}
    pushes = [
        repository.pushed_on
        for term in owner.repos
        if (repository := by_name.get(term.value.lower())) is not None
        and repository.pushed_on is not None
    ]
    return _date(max(pushes)) if pushes else "—"


# --------------------------------------------------------------------------- the home page


@page(1, "README.md", "Portfolio overview", "Overview")
def home(view: OverviewInput) -> list[str]:
    """The numbers at a glance, what needs attention, this week, where the week's work went
    and the latest decisions."""
    return [
        *_section("At a glance", _glance(view)),
        *_section("Needs attention", _attention(view)),
        *_section("This week", _this_week(view)),
        *_section("Where the work went", _work(view)),
        *_section("Latest decisions", _latest(view)),
    ]


def _glance(view: OverviewInput) -> list[str]:
    portfolio, today = view.portfolio, view.today
    thresholds = portfolio.config.thresholds
    focus = this_weeks_focus(portfolio, today)
    if focus is None:
        focused = "**none recorded**"
    else:
        focused = f"{_entity(portfolio, focus.ids[0])}, recorded {focus.date}"
    if view.clocks is None:
        stale = "— (no clocks without the git history)"
    else:
        stale = f"{len(_stale(view))} (stale_days: {thresholds.stale_days})"
    waiting = len(_products(portfolio, "paused", "dormant"))
    overdue = len(_overdue(view))
    open_risks = [risk for risk in portfolio.risks if risk.counts_as_open(today)]
    severe = sum(1 for risk in open_risks if risk.severity in SEVERE)
    states = [kernel_state(portfolio, kernel).state for kernel in portfolio.kernels]
    kernels = ", ".join(f"{states.count(s)} {s}" for s in ("done", "extracted", "planned"))
    rows = [
        (
            "[Active products](products.md#active)",
            f"{len(_products(portfolio, 'active'))} of {thresholds.wip_limit} (wip_limit)",
        ),
        ("Focus this week", focused),
        ("Stale products", stale),
        ("[Ideas](products.md#ideas)", str(len(_products(portfolio, "idea")))),
        (
            "[Paused or dormant](products.md#paused-and-dormant)",
            f"{waiting}, {_count(overdue, 'review')} overdue" if overdue else str(waiting),
        ),
        ("[Archived](products.md#archived)", str(len(_products(portfolio, "archived")))),
        ("[Kernels](products.md#kernels)", f"{len(states)}: {kernels}" if states else "0"),
        ("[Open risks](risks.md#risks)", f"{len(open_risks)}, {severe} high or critical"),
        (
            "[Findings](risks.md#findings)",
            f"{len(portfolio.findings)}, {len(_expired(view))} expired",
        ),
        ("[Copy-paste debt](risks.md#copy-paste-debt)", str(len(copies(portfolio)))),
        ("[Repositories worked on](repositories.md)", _worked_summary(view)),
        ("Data last committed", _date(view.last_data_commit)),
    ]
    return _table(("Measure", "Now"), rows)


def _worked_summary(view: OverviewInput) -> str:
    account, scan = view.account, view.account.scan
    if scan is None:
        return "**the scan failed**" if account.failed else "— (the account is not scanned)"
    worked = sum(1 for r in shown(scan) if worked_on(r, scan) is not None)
    outside = len(outside_portfolio(view.portfolio, scan))
    only = ", **public repositories only**" if not scan.sees_private else ""
    return f"{worked} since {scan.since}, {outside} outside the portfolio{only}"


def _attention(view: OverviewInput) -> list[str]:
    """What the weekly report and the dashboard make stand out, each with where to look."""
    portfolio, today = view.portfolio, view.today
    items = []
    stale = _stale(view)
    if stale:
        limit = portfolio.config.thresholds.stale_days
        names = [f"{label(p.name, p.id or '')}, {_days(c.days)}" for p, c in stale]
        items.append(
            f"**Stale:** {_joined(names)} — the clock is past stale_days ({limit}). See "
            "[the active products](products.md#active)."
        )
    overdue = _overdue(view)
    if overdue:
        names = [f"{label(p.name, p.id or '')}, due {p.review_by}" for p in overdue]
        items.append(
            f"**Reviews overdue:** {_joined(names)}. See "
            "[paused and dormant](products.md#paused-and-dormant)."
        )
    ended = _ended(view)
    if ended:
        names = [f"{label(r.title, r.id or '')}, accepted until {r.accepted_until}" for r in ended]
        items.append(
            f"**Acceptances ended:** {_joined(names)} — they count as open again. See "
            "[the risks](risks.md#risks)."
        )
    severe = sorted(
        (r for r in portfolio.risks if r.state == "open" and r.severity in SEVERE),
        key=lambda r: (-_severity(r), r.id or ""),
    )
    if severe:
        names = [f"{label(r.title, r.id or '')}, {r.severity}" for r in severe]
        items.append(
            f"**Open high or critical risks:** {_joined(names)}. See [the risks](risks.md#risks)."
        )
    expired = _expired(view)
    if expired:
        names = [f"{label(f.result, f.id or '')}, held until {until}" for until, f in expired]
        items.append(
            f"**Expired findings:** {_joined(names)} — check each again before it is used. "
            "See [the findings](risks.md#findings)."
        )
    debt = copies(portfolio)
    if debt:
        names = [
            f"{label(p.name, p.id or '')} carries a copy of {label(k.name, k.id or '')}"
            for p, k in debt
        ]
        items.append(
            f"**Copy-paste debt:** {_joined(names)}. See "
            "[the copy-paste debt](risks.md#copy-paste-debt)."
        )
    items += _account_attention(view)
    if this_weeks_focus(portfolio, today) is None:
        items.append(
            f"**No focus recorded this week.** Record one in {DECISIONS_FILE} as "
            f"`## {today} · <product> · focus`."
        )
    if not items:
        return ["Nothing needs attention."]
    return [f"- {item}" for item in items]


def _account_attention(view: OverviewInput) -> list[str]:
    account, portfolio = view.account, view.portfolio
    scan = account.scan
    if scan is None:
        if account.failed:
            return [f"**The account was not scanned.** {md(account.problem)}."]
        return []
    items = []
    blind = blind_spot(scan)
    if blind:
        items.append(f"**The token sees only public repositories:** {md(blind)}.")
    outside = outside_portfolio(portfolio, scan)
    if outside:
        items.append(
            f"**Work outside the portfolio:** {_count(len(outside), 'repository')} you worked "
            f"on since {scan.since} {'belongs' if len(outside) == 1 else 'belong'} to no "
            "product or kernel. See [the week's repositories](repositories.md#worked-on-this-week)."
        )
    inactive = inactive_work(portfolio, scan)
    if inactive:
        names = [
            f"{label(w.product.name, w.product.id or '')}, {w.product.status}, in "
            f"{_repository(view, w.repository.name)}"
            for w in inactive
        ]
        items.append(f"**Products that are not active, worked on:** {_joined(names)}.")
    unknown = unknown_repositories(portfolio, scan)
    if unknown:
        names = [
            f"{_repository(view, u.term.value, link=False)}, listed by "
            f"{label(u.owner.name, u.owner.id or '')}"
            for u in unknown
        ]
        items.append(
            f"**Listed repositories the account does not have:** {_joined(names)}. See "
            "[the repositories](repositories.md#listed-but-not-found)."
        )
    return items


def _this_week(view: OverviewInput) -> list[str]:
    portfolio = view.portfolio
    focus = this_weeks_focus(portfolio, view.today)
    if focus is None:
        lines = ["**No focus recorded this week.**"]
    else:
        lines = [f"Focus: {_entity(portfolio, focus.ids[0])}, recorded {focus.date}."]
    active = _products(portfolio, "active")
    if not active:
        return [*lines, "", "No product is active."]
    if view.clocks is None:
        lines += ["", f"The clocks are not shown: {md(view.no_clocks)}."]
    scan = view.account.scan
    headers = ["Product", "Next action", "Clock"]
    rows = []
    for product in active:
        row = [
            label(product.name, product.id or ""),
            md(product.next_action),
            _clock(view, product.id or ""),
        ]
        rows.append(row if scan is None else [*row, _last_push(scan, product)])
    return [*lines, "", *_table(headers if scan is None else [*headers, "Last push"], rows)]


def _work(view: OverviewInput) -> list[str]:
    """The repositories with the owner's activity in the window, by the product or kernel
    that lists them, as a Mermaid pie."""
    account = view.account
    scan = account.scan
    if scan is None:
        return [f"The account was not scanned: {md(account.problem)}."]
    visible = shown(scan)
    worked = [r for r in visible if worked_on(r, scan) is not None]
    if not worked:
        return [
            (
                f"No activity of yours since {scan.since} in the "
                f"{_count(len(visible), 'repository')} scanned."
            )
        ]
    lines = [
        (
            f"Your activity since {scan.since} is in {len(worked)} of the "
            f"{_count(len(visible), 'repository')} scanned. The chart groups them by the "
            "product or kernel that lists them, and "
            "[the repositories page](repositories.md#worked-on-this-week) names them."
        ),
        "",
        "```mermaid",
        "pie showData",
        f"    title Repositories with your activity since {scan.since}",
        *(f'    "{name}" : {count}' for name, count in _slices(view, worked)),
        "```",
    ]
    if not scan.sees_private:
        lines += [
            "",
            "The token sees only public repositories, so work in private ones is missing.",
        ]
    return lines


def _slices(view: OverviewInput, worked: Sequence[AccountRepository]) -> list[tuple[str, int]]:
    """The pie's slices, the largest first: one for each product or kernel, one for the
    ignored repositories and one for those outside the portfolio."""
    listed = listing(view.portfolio)
    counts: dict[str, int] = {}
    names: dict[str, tuple[str, str]] = {}  # a slice's key: its label, and its id
    for repository in worked:
        owner = listed.get(repository.name.lower())
        if isinstance(owner, Product):
            key = f"product {owner.id}"
            status = "" if owner.status == "active" else f" ({owner.status})"
            names[key] = (chart_label(owner.name, owner.id or "") + status, owner.id or "")
        elif owner is not None:
            key = f"kernel {owner.id}"
            names[key] = (chart_label(owner.name, owner.id or "") + " (kernel)", owner.id or "")
        elif ignored(view.portfolio, repository.name):
            key, names[key] = "ignored", ("Ignored", "")
        else:
            key, names[key] = "outside", ("Outside the portfolio", "")
        counts[key] = counts.get(key, 0) + 1
    # Mermaid joins slices that share a label, so a label used twice takes its id along.
    taken = [names[key][0] for key in counts]
    slices = []
    for key, count in counts.items():
        name, ident = names[key]
        slices.append((name if taken.count(name) == 1 else f"{name} {ident}", count))
    return sorted(slices, key=lambda pair: (-pair[1], pair[0]))


def _latest(view: OverviewInput) -> list[str]:
    portfolio = view.portfolio
    every = newest_first(portfolio)
    if not every:
        return ["No decision is recorded yet."]
    lines = [
        f"- {d.date} · {md(d.type)} · {', '.join(_entity(portfolio, i) for i in d.ids)}"
        for d in every[:LATEST_DECISIONS]
    ]
    return [*lines, "", "Every decision, with its text: [Decisions](decisions.md)."]


# --------------------------------------------------------------------------- products


@page(2, "products.md", "Products", "Products")
def products_page(view: OverviewInput) -> list[str]:
    """Every product by status and every kernel; the review dates on a timeline."""
    return [
        *_section("Active", _active(view)),
        *_section("Ideas", _ideas(view)),
        *_section("Paused and dormant", _waiting(view)),
        *_section("Archived", _archived(view)),
        *_section("Kernels", _kernels(view)),
    ]


def _active(view: OverviewInput) -> list[str]:
    portfolio = view.portfolio
    products = _products(portfolio, "active")
    lines = [f"{len(products)} of at most {portfolio.config.thresholds.wip_limit} (wip_limit)."]
    if not products:
        return [*lines, "", "No product is active."]
    if view.clocks is None:
        lines += ["", f"The clocks are not shown: {md(view.no_clocks)}."]
    focus = this_weeks_focus(portfolio, view.today)
    scan = view.account.scan
    rows = []
    for product in products:
        pid = product.id or ""
        name = label(product.name, pid)
        if focus is not None and focus.ids[0] == pid:
            name += ", **focus**"
        row = [
            name,
            md(product.next_action),
            _clock(view, pid),
            _terms(product.capabilities),
            _feeds(view, product),
            _listed(view, product),
        ]
        rows.append(row if scan is None else [*row, _last_push(scan, product)])
    headers = ["Product", "Next action", "Clock", "Capabilities", "Kernels", "Repositories"]
    return [*lines, "", *_table(headers if scan is None else [*headers, "Last push"], rows)]


def _ideas(view: OverviewInput) -> list[str]:
    portfolio = view.portfolio
    products = _products(portfolio, "idea")
    if not products:
        return ["No idea is registered."]
    rows = [
        (
            label(p.name, p.id or ""),
            _terms(p.capabilities),
            _decision_ref(latest_about(portfolio, p.id or "")),
        )
        for p in products
    ]
    return [
        f"{_count(len(products), 'idea')}, not yet through the idea gate.",
        "",
        *_table(("Idea", "Capabilities", "Latest decision"), rows),
    ]


def _waiting(view: OverviewInput) -> list[str]:
    """Products that wait for a review, the soonest first, and their reviews on a timeline."""
    products = sorted(
        _products(view.portfolio, "paused", "dormant"),
        key=lambda p: (p.review_by or dt.date.max, p.id or ""),
    )
    if not products:
        return ["No product is paused or dormant."]
    scan = view.account.scan
    rows = [
        [
            label(p.name, p.id or ""),
            md(p.status),
            md(p.status_reason) or "—",
            _review(p.review_by, view.today),
            md(p.next_action) or "—",
            *([] if scan is None else [_last_push(scan, p)]),
        ]
        for p in products
    ]
    headers = ["Product", "Status", "Reason", "Review by", "Next action"]
    table = _table(headers if scan is None else [*headers, "Last push"], rows)
    return [*table, *_review_chart(view, products)]


def _review(review_by: dt.date | None, today: dt.date) -> str:
    if review_by is None:
        return "—"
    days = (review_by - today).days
    if days < 0:
        return f"{review_by}, **overdue** by {_days(-days)}"
    return f"{review_by}, {'today' if days == 0 else f'in {_days(days)}'}"


def _review_chart(view: OverviewInput, products: Sequence[Product]) -> list[str]:
    """The review dates as Mermaid milestones, with today's: an overdue review is marked
    critical. Today is the page's, not the reader's, so Mermaid's own marker is off."""
    lines = []
    for status in ("paused", "dormant"):
        dated = [p for p in products if p.status == status and p.review_by is not None]
        if dated:
            lines.append(f"    section {status.capitalize()}")
        for product in dated:
            overdue = product.review_by is not None and product.review_by < view.today
            name = chart_label(product.name, product.id or "")
            tags = "crit, milestone" if overdue else "milestone"
            lines.append(f"    Review of {name} : {tags}, {product.review_by}, 0d")
    if not lines:
        return []
    return [
        "",
        "```mermaid",
        "gantt",
        "    title Review dates",
        "    dateFormat YYYY-MM-DD",
        "    axisFormat %Y-%m-%d",
        "    todayMarker off",
        f"    Today : active, milestone, {view.today}, 0d",
        *lines,
        "```",
    ]


def _archived(view: OverviewInput) -> list[str]:
    portfolio = view.portfolio
    products = _products(portfolio, "archived")
    if not products:
        return ["No product is archived."]
    rows = [
        (label(p.name, p.id or ""), _decision_ref(latest_about(portfolio, p.id or "")))
        for p in products
    ]
    return _table(("Product", "Latest decision"), rows)


def _kernels(view: OverviewInput) -> list[str]:
    """Each kernel's state (K1) and who uses it how; a copy is copy-paste debt (K2)."""
    portfolio = view.portfolio
    if not portfolio.kernels:
        return ["No kernel is registered."]
    rows = []
    for kernel in portfolio.kernels:
        kid = kernel.id or ""
        users = [
            _joined([label(p.name, p.id or "") for p in consumers(portfolio, kid, mode)])
            for mode in ("package", "copy", "planned")
        ]
        rows.append(
            (
                label(kernel.name, kid),
                kernel_state(portfolio, kernel).summary,
                _terms(kernel.capabilities),
                *users,
                _listed(view, kernel),
            )
        )
    headers = (
        "Kernel",
        "State",
        "Capabilities",
        "As a package",
        "As a copy",
        "Planned",
        "Repositories",
    )
    return _table(headers, rows)


# --------------------------------------------------------------------------- repositories


@page(3, "repositories.md", "Repositories", "Repositories")
def repositories_page(view: OverviewInput) -> list[str]:
    """The account's repositories (§7.12): those worked on in the window first, then all of
    them, each with the product or kernel that lists it."""
    account = view.account
    scan = account.scan
    if scan is None:
        return [f"The account was not scanned: {md(account.problem)}.", "", *_listing(view)]
    place = _placer(view, scan)
    return [
        *_scan_notes(scan),
        "",
        *_section("Worked on this week", _week(view, scan, place)),
        *_section("All repositories", _every(view, scan, place)),
        *_not_found(view, scan),
    ]


def _placer(view: OverviewInput, scan: AccountScan) -> Callable[[AccountRepository], str]:
    """Where a repository belongs: the product or kernel that lists it, ignored, or outside
    the portfolio. Work outside the plan (A1, A2) is in bold."""
    portfolio = view.portfolio
    listed = listing(portfolio)
    attention = {w.repository.name for w in outside_portfolio(portfolio, scan)}
    attention |= {w.repository.name for w in inactive_work(portfolio, scan)}

    def place(repository: AccountRepository) -> str:
        owner = listed.get(repository.name.lower())
        bold = repository.name in attention
        if isinstance(owner, Product):
            status = f"**{md(owner.status)}**" if bold else md(owner.status)
            return f"{label(owner.name, owner.id or '')}, {status}"
        if owner is not None:
            return f"{label(owner.name, owner.id or '')}, kernel"
        if ignored(portfolio, repository.name):
            return "ignored"
        return "**outside the portfolio**" if bold else "—"

    return place


def _scan_notes(scan: AccountScan) -> list[str]:
    """How much the scan saw, and what it could not see."""
    visible = shown(scan)
    worked = sum(1 for r in visible if worked_on(r, scan) is not None)
    public, private = visibility(scan)
    split = "" if scan.hide_private else f" ({public} public, {private} private)"
    notes = []
    blind = blind_spot(scan)
    if blind:
        notes.append(f"**The token sees only public repositories:** {md(blind)}.")
    notes.append(
        f"{_count(len(visible), 'repository')}{split} of {md(scan.login)} scanned; your "
        f"activity since {scan.since} is in {worked} of them."
    )
    unreadable = sum(1 for r in visible if r.activity == "unreadable")
    if unreadable:
        notes.append(
            f"Your activity could not be told apart from other pushes in "
            f"{_count(unreadable, 'repository')}: {md(scan.unreadable)}. There, a push by "
            "anyone counts."
        )
    if scan.hide_private:
        notes.append("allow_public is set, so private repositories are left out.")
    return _paragraphs(notes)


def _week(
    view: OverviewInput, scan: AccountScan, place: Callable[[AccountRepository], str]
) -> list[str]:
    """The repositories with the owner's activity in the window, the latest first."""
    worked = sorted(
        ((r, day) for r in shown(scan) if (day := worked_on(r, scan)) is not None),
        key=lambda pair: (-pair[1].toordinal(), pair[0].name.lower()),
    )
    if not worked:
        return [f"No activity of yours since {scan.since}."]
    rows = [
        (
            _named(view, r),
            place(r),
            f"{day}, a push by anyone" if r.activity == "unreadable" else str(day),
        )
        for r, day in worked
    ]
    return [
        f"Since {scan.since}, the latest first.",
        "",
        *_table(("Repository", "In the portfolio", "Your latest activity"), rows),
    ]


def _every(
    view: OverviewInput, scan: AccountScan, place: Callable[[AccountRepository], str]
) -> list[str]:
    """Every repository, the latest push first; forks and archived repositories that repos
    does not list are folded away."""
    listed = listing(view.portfolio)
    every = sorted(
        shown(scan), key=lambda r: (r.pushed_on is None, -_ordinal(r.pushed_on), r.name.lower())
    )
    if not every:
        return ["The account has no repository."]
    main = [r for r in every if r.name.lower() in listed or not (r.fork or r.archived)]
    folded = [r for r in every if r.name.lower() not in listed and (r.fork or r.archived)]
    lines = (
        [
            f"{_count(len(main), 'repository')}, the latest push first.",
            "",
            *_table(
                ("Repository", "In the portfolio", "Last push"),
                [(_named(view, r), place(r), _date(r.pushed_on)) for r in main],
            ),
        ]
        if main
        else ["Every repository is a fork or archived."]
    )
    if folded:
        rows = [(_named(view, r), _date(r.pushed_on)) for r in folded]
        lines += [
            "",
            "<details>",
            f"<summary>Forks and archived repositories ({len(folded)})</summary>",
            "",
            *_table(("Repository", "Last push"), rows),
            "",
            "</details>",
        ]
    return lines


def _not_found(view: OverviewInput, scan: AccountScan) -> list[str]:
    """The listed repositories the account does not have (A3)."""
    unknown = unknown_repositories(view.portfolio, scan)
    if not unknown:
        return []
    rows = [
        (_repository(view, u.term.value, link=False), label(u.owner.name, u.owner.id or ""))
        for u in unknown
    ]
    return _section(
        "Listed but not found",
        [
            (
                "Listed in repos, but not among the account's repositories — a typo, a renamed "
                "repository or a deleted one:"
            ),
            "",
            *_table(("Repository", "Listed by"), rows),
        ],
    )


def _listing(view: OverviewInput) -> list[str]:
    """Without a scan: the repositories the portfolio lists."""
    owners: tuple[Product | Kernel, ...] = (*view.portfolio.products, *view.portfolio.kernels)
    listed = sorted(
        ((term.value, owner) for owner in owners for term in owner.repos),
        key=lambda pair: pair[0].lower(),
    )
    if not listed:
        return _section("Listed in the portfolio", ["No product or kernel lists a repository."])
    rows = [(_repository(view, name), label(owner.name, owner.id or "")) for name, owner in listed]
    return _section("Listed in the portfolio", _table(("Repository", "Listed by"), rows))


def _ordinal(day: dt.date | None) -> int:
    return day.toordinal() if day is not None else 0


def _named(view: OverviewInput, repository: AccountRepository) -> str:
    flags = [
        kind
        for kind, flag in (
            ("private", repository.private),
            ("fork", repository.fork),
            ("archived", repository.archived),
        )
        if flag
    ]
    return " · ".join([_repository(view, repository.name), *flags])


# --------------------------------------------------------------------------- risks


@page(4, "risks.md", "Risks and findings", "Risks")
def risks_page(view: OverviewInput) -> list[str]:
    """The risks, those that count as open first; the findings; the copy-paste debt."""
    return [
        *_section("Risks", _risks(view)),
        *_section("Findings", _findings(view)),
        *_section("Copy-paste debt", _debt(view)),
    ]


def _risks(view: OverviewInput) -> list[str]:
    portfolio, today = view.portfolio, view.today
    if not portfolio.risks:
        return ["No risk is registered."]

    def order(risk: Risk) -> tuple[int, int, str]:
        group = 0 if risk.counts_as_open(today) else 1 if risk.state == "accepted" else 2
        return group, -_severity(risk), risk.id or ""

    risks = sorted(portfolio.risks, key=order)
    opened = sum(1 for risk in risks if risk.counts_as_open(today))
    rows = [
        (
            label(risk.title, risk.id or ""),
            _entity(portfolio, risk.scope),
            f"**{risk.severity}**" if risk.severity in SEVERE else md(risk.severity),
            _terms(risk.applies_to),
            _risk_state(risk, today),
        )
        for risk in risks
    ]
    verb = "counts as open and comes" if opened == 1 else "count as open and come"
    return [
        (
            f"{_count(len(risks), 'risk')}; {opened} {verb} first — open, or accepted past "
            "accepted_until."
        ),
        "",
        *_table(("Risk", "Scope", "Severity", "Applies to", "State"), rows),
    ]


def _risk_state(risk: Risk, today: dt.date) -> str:
    if risk.state == "accepted":
        if risk.acceptance_holds(today):
            return f"accepted until {risk.accepted_until}"
        return f"**acceptance ended** {risk.accepted_until}; counts as open"
    return "**open**" if risk.state == "open" else md(risk.state)


def _findings(view: OverviewInput) -> list[str]:
    """What was verified and until when it holds (P2), the soonest to expire first."""
    portfolio, today = view.portfolio, view.today
    config = portfolio.config
    if not portfolio.findings:
        return ["No finding is recorded."]
    dated = sorted(
        ((config.expiry(f), f) for f in portfolio.findings),
        key=lambda pair: (pair[0] or dt.date.max, pair[1].id or ""),
    )
    rows = []
    for until, finding in dated:
        what = label(finding.result, finding.id or "")
        if finding.evidence:
            what += f" — evidence: {md(finding.evidence)}"
        holds = _date(until)
        if until is not None and until < today:
            holds += ", **expired**"
        rows.append(
            (
                what,
                _entity(portfolio, finding.subject),
                md(finding.type),
                _date(finding.checked_on),
                holds,
                _terms(finding.used_in),
            )
        )
    expired = len(_expired(view))
    return [
        (
            f"{_count(len(rows), 'finding')}, the soonest to expire first; {expired} expired — "
            "check an expired one again before it is used."
        ),
        "",
        *_table(("Finding", "Subject", "Type", "Checked on", "Holds until", "Used in"), rows),
    ]


def _debt(view: OverviewInput) -> list[str]:
    portfolio = view.portfolio
    debts = copies(portfolio)
    if not debts:
        return ["No product carries a copy of a kernel."]
    rows = [
        (
            label(product.name, product.id or ""),
            label(kernel.name, kernel.id or ""),
            kernel_state(portfolio, kernel).summary,
        )
        for product, kernel in debts
    ]
    return [
        "Products that carry a copy of a kernel instead of using it as a package:",
        "",
        *_table(("Product", "Kernel", "Kernel state"), rows),
    ]


# --------------------------------------------------------------------------- decisions


@page(5, "decisions.md", "Decisions", "Decisions")
def decisions_page(view: OverviewInput) -> list[str]:
    """Every decision, newest first, with its text."""
    portfolio = view.portfolio
    every = newest_first(portfolio)
    if not every:
        return ["No decision is recorded yet."]
    lines = [
        "The only decision." if len(every) == 1 else f"All {len(every)} decisions, newest first."
    ]
    for decision in every:
        names = ", ".join(_entity(portfolio, ident) for ident in decision.ids)
        lines += ["", f"## {decision.date} · {md(decision.type)} · {names}"]
        if decision.text:
            lines += ["", *_quoted(decision.text)]
    return lines
