"""The views as commands: ``dashboard`` (V1), ``export`` (V2) and ``overview`` (V3) — where
their output goes, and what happens on data that does not validate or on a request they
cannot meet."""

from __future__ import annotations

import posixpath
from pathlib import Path

import pytest

from helpers import copy_fixture, run_cli

NO_GIT = "note: the dashboard shows no clocks — the data directory is not inside a git repository\n"


@pytest.fixture
def data(tmp_path: Path) -> Path:
    return copy_fixture("valid", tmp_path / "valid")


def test_dashboard_writes_the_page_to_the_output_file(data: Path, tmp_path: Path) -> None:
    page = tmp_path / "dashboard.html"

    run = run_cli(["dashboard", "--path", str(data), "--output", str(page)])

    assert run.code == 0, run.err
    assert run.out == ""
    assert page.read_text(encoding="utf-8").startswith("<!doctype html>\n")
    assert run.err == NO_GIT + (
        f"portfolio-ops dashboard: wrote {page} — 5 products, 1 kernel, 2 risks, 2 findings "
        "and 3 decisions\n"
    )


@pytest.mark.parametrize("output", [[], ["--output", "-"]], ids=["default", "dash"])
def test_without_a_file_the_page_goes_to_standard_output(data: Path, output: list[str]) -> None:
    run = run_cli(["dashboard", "--path", str(data), *output])

    assert run.code == 0, run.err
    assert run.out.startswith("<!doctype html>\n")
    assert run.out.endswith("</html>\n")
    assert "wrote standard output" in run.err


def test_today_is_the_day_the_page_shows(data: Path) -> None:
    run = run_cli(["dashboard", "--path", str(data), "--today", "2026-10-15"])

    assert "<title>Portfolio dashboard — 2026-10-15</title>" in run.out
    assert '<span class="badge attention">overdue</span><span class="sub">14 days ago' in run.out


def test_the_dashboard_shows_only_data_that_validates(tmp_path: Path) -> None:
    root = copy_fixture("S4", tmp_path / "S4")
    page = tmp_path / "dashboard.html"

    run = run_cli(["dashboard", "--path", str(root), "--output", str(page)])

    assert run.code == 1
    assert run.out == ""
    assert not page.exists()
    assert run.err.startswith("error S4 ")
    assert "the data in" in run.err
    assert "does not validate" in run.err


def test_an_output_that_cannot_be_written_exits_2(data: Path, tmp_path: Path) -> None:
    page = tmp_path / "missing" / "dashboard.html"

    run = run_cli(["dashboard", "--path", str(data), "--output", str(page)])

    assert run.code == 2
    assert run.out == ""
    assert f"cannot write {page}: " in run.err


def test_export_prints_the_markdown_and_says_how_much_it_holds(data: Path) -> None:
    run = run_cli(["export", "--path", str(data)])

    assert run.code == 0, run.err
    assert run.out.startswith("# Portfolio context — 2026-09-22\n")
    assert run.err == (
        f"portfolio-ops export: {len(run.out)} of at most 12000 characters, with 3 of 3 decisions\n"
    )


def test_export_leaves_out_the_oldest_decisions_to_stay_within_max_chars(data: Path) -> None:
    run = run_cli(["export", "--path", str(data), "--max-chars", "1000"])

    assert run.code == 0, run.err
    assert len(run.out) <= 1000
    assert "The rest are left out to stay within 1000 characters" in run.out
    assert run.err.endswith(" of at most 1000 characters, with 1 of 3 decisions\n")


def test_a_limit_the_fixed_parts_do_not_fit_in_exits_2(data: Path) -> None:
    run = run_cli(["export", "--path", str(data), "--max-chars", "100"])

    assert run.code == 2
    assert run.out == ""
    assert "the export needs at least " in run.err
    assert "raise --max-chars to " in run.err


@pytest.mark.parametrize("value", ["0", "-5", "many", "1.5"])
def test_max_chars_is_a_whole_number_above_0(data: Path, value: str) -> None:
    run = run_cli(["export", "--path", str(data), "--max-chars", value])

    assert run.code == 2
    assert f"expected a whole number above 0, got '{value}'" in run.err


def test_export_shows_only_data_that_validates(tmp_path: Path) -> None:
    root = copy_fixture("S4", tmp_path / "S4")

    run = run_cli(["export", "--path", str(root)])

    assert run.code == 1
    assert run.out == ""
    assert run.err.startswith("error S4 ")


# ------------------------------------------------------------------ overview (V3)

PAGE_FILES = ["README.md", "decisions.md", "products.md", "repositories.md", "risks.md"]


def pages_in(directory: Path) -> list[str]:
    return sorted(path.name for path in directory.iterdir())


def test_overview_writes_its_pages_to_overview_in_the_data_directory(data: Path) -> None:
    run = run_cli(["overview", "--path", str(data)])

    assert run.code == 0, run.err
    assert run.out == ""
    assert pages_in(data / "overview") == PAGE_FILES
    home = (data / "overview" / "README.md").read_text(encoding="utf-8")
    assert home.startswith("<!-- Generated by portfolio-ops.")
    assert run.err == NO_GIT.replace("dashboard", "overview") + (
        f"portfolio-ops overview: wrote 5 pages to {data.as_posix()}/overview — 5 products, "
        "1 kernel, 2 risks, 2 findings and 3 decisions\n"
    )


def test_overview_writes_to_the_directory_output_names(data: Path, tmp_path: Path) -> None:
    pages = tmp_path / "pages" / "nested"

    run = run_cli(
        ["overview", "--path", str(data), "--output", str(pages), "--today", "2026-10-15"]
    )

    assert run.code == 0, run.err
    assert pages_in(pages) == PAGE_FILES
    assert not (data / "overview").exists()
    products = (pages / "products.md").read_text(encoding="utf-8")
    assert "Generated by portfolio-ops for 2026-10-15 (UTC)." in products
    assert "| Beta (`beta`) | paused |" in products


def test_overview_rewrites_its_own_pages(data: Path) -> None:
    assert run_cli(["overview", "--path", str(data), "--today", "2026-09-22"]).code == 0

    run = run_cli(["overview", "--path", str(data), "--today", "2026-09-23"])

    assert run.code == 0, run.err
    home = (data / "overview" / "README.md").read_text(encoding="utf-8")
    assert "Generated by portfolio-ops for 2026-09-23 (UTC)." in home


def test_overview_never_overwrites_a_file_it_did_not_write(data: Path) -> None:
    notes = "# My portfolio\n\nNotes of my own.\n"
    (data / "README.md").write_text(notes, encoding="utf-8")

    run = run_cli(["overview", "--path", str(data), "--output", str(data)])

    assert run.code == 2
    assert (data / "README.md").read_text(encoding="utf-8") == notes
    assert not (data / "products.md").exists()
    assert run.err.endswith(
        f"error: {posixpath.join(str(data), 'README.md')} was not written by portfolio-ops, "
        "and the overview would overwrite it — choose another directory with --output\n"
    )


def test_the_overview_shows_only_data_that_validates(tmp_path: Path) -> None:
    root = copy_fixture("S4", tmp_path / "S4")

    run = run_cli(["overview", "--path", str(root)])

    assert run.code == 1
    assert run.out == ""
    assert not (root / "overview").exists()
    assert run.err.startswith("error S4 ")
    assert "does not validate" in run.err


def test_an_overview_directory_that_cannot_be_made_exits_2(data: Path, tmp_path: Path) -> None:
    blocker = tmp_path / "a-file"
    blocker.write_text("not a directory\n", encoding="utf-8")

    run = run_cli(["overview", "--path", str(data), "--output", str(blocker / "pages")])

    assert run.code == 2
    assert f"cannot write the overview to {blocker / 'pages'}: " in run.err
